#[derive(Debug, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum SystemColor {
    AccentColor,
    AccentColorText,
    ActiveText,
    ButtonBorder,
    ButtonFace,
    ButtonText,
    Canvas,
    CanvasText,
    Field,
    FieldText,
    GrayText,
    Highlight,
    HighlightText,
    LinkText,
    Mark,
    MarkText,
    SelectedItem,
    SelectedItemText,
    VisitedText,
}

#[derive(Debug, Default, Clone, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub enum NamedColor {
    AliceBlue,
    AntiqueWhite,
    Aqua,
    Aquamarine,
    Azure,
    Beige,
    Bisque,
    #[default]
    Black,
    BlanchedAlmond,
    Blue,
    BlueViolet,
    Brown,
    BurlyWood,
    CadetBlue,
    Chartreuse,
    Chocolate,
    Coral,
    CornflowerBlue,
    Cornsilk,
    Crimson,
    Cyan,
    DarkBlue,
    DarkCyan,
    DarkGoldenRod,
    DarkGray,
    DarkGreen,
    DarkKhaki,
    DarkMagenta,
    DarkOliveGreen,
    DarkOrange,
    DarkOrchid,
    DarkRed,
    DarkSalmon,
    DarkSeaGreen,
    DarkSlateBlue,
    DarkSlateGray,
    //DarkSlateGrey,
    DarkTurquoise,
    DarkViolet,
    DeepPink,
    DeepSkyBlue,
    DimGray,
    //DimGrey,
    DodgerBlue,
    FireBrick,
    FloralWhite,
    ForestGreen,
    Fuchsia,
    Gainsboro,
    GhostWhite,
    Gold,
    GoldenRod,
    Gray,
    Green,
    GreenYellow,
    //Grey,
    HoneyDew,
    HotPink,
    IndianRed,
    Indigo,
    Ivory,
    Khaki,
    Lavender,
    LavenderBlush,
    LawnGreen,
    LemonChiffon,
    LightBlue,
    LightCoral,
    LightCyan,
    LightGoldenRodYellow,
    LightGray,
    LightGreen,
    //LightGrey,
    LightPink,
    LightSalmon,
    LightSeaGreen,
    LightSkyBlue,
    LightSlateGray,
    //LightSlateGrey,
    LightSteelBlue,
    LightYellow,
    Lime,
    LimeGreen,
    Linen,
    Magenta,
    Maroon,
    MediumAquaMarine,
    MediumBlue,
    MediumOrchid,
    MediumPurple,
    MediumSeaGreen,
    MediumSlateBlue,
    MediumSpringGreen,
    MediumTurquoise,
    MediumVioletRed,
    MidnightBlue,
    MintCream,
    MistyRose,
    Moccasin,
    NavajoWhite,
    Navy,
    OldLace,
    Olive,
    OliveDrab,
    Orange,
    OrangeRed,
    Orchid,
    PaleGoldenRod,
    PaleGreen,
    PaleTurquoise,
    PaleVioletRed,
    PapayaWhip,
    PeachPuff,
    Peru,
    Pink,
    Plum,
    PowderBlue,
    Purple,
    RebeccaPurple,
    Red,
    RosyBrown,
    RoyalBlue,
    SaddleBrown,
    Salmon,
    SandyBrown,
    SeaGreen,
    SeaShell,
    Sienna,
    Silver,
    SkyBlue,
    SlateBlue,
    SlateGray,
    //SlateGrey,
    Snow,
    SpringGreen,
    SteelBlue,
    Tan,
    Teal,
    Thistle,
    Tomato,
    Transparent,
    Turquoise,
    Violet,
    Wheat,
    White,
    WhiteSmoke,
    Yellow,
    YellowGreen,
}

#[derive(Debug, Clone)]
pub enum SRGBAColor {
    RGB(u8, u8, u8),
    RGBA(u8, u8, u8, f32),
    HSL(f32, f32, f32),
    HSLA(f32, f32, f32, f32),
    HWB(f32, f32, f32),
}

#[derive(Debug, Clone)]
pub enum CIELAB {
    Lab(f32, f32, f32),
    Lch(f32, f32, f32),
}

#[derive(Debug, Clone)]
pub enum Oklab {
    Oklab(f32, f32, f32),
    Oklch(f32, f32, f32),
}

#[derive(Clone, Debug)]
pub enum FunctionColor {
    SRGBA(SRGBAColor),
    CIELAB(CIELAB),
    Oklab(Oklab),
}

#[derive(Clone, Debug)]
pub enum Color {
    System(SystemColor),
    Named(NamedColor),
    Hex([u8; 6]),
    Functional(FunctionColor),
    CurrentColor,
}

impl From<&str> for SystemColor {
    fn from(value: &str) -> Self {
        match value {
            "AccentColor" => SystemColor::AccentColor,
            "AccentColorText" => SystemColor::AccentColorText,
            "ActiveText" => SystemColor::ActiveText,
            "ButtonBorder" => SystemColor::ButtonBorder,
            "ButtonFace" => SystemColor::ButtonFace,
            "ButtonText" => SystemColor::ButtonText,
            "Canvas" => SystemColor::Canvas,
            "CanvasText" => SystemColor::CanvasText,
            "Field" => SystemColor::Field,
            "FieldText" => SystemColor::FieldText,
            "GrayText" => SystemColor::GrayText,
            "Highlight" => SystemColor::Highlight,
            "HighlightText" => SystemColor::HighlightText,
            "LinkText" => SystemColor::LinkText,
            "Mark" => SystemColor::Mark,
            "MarkText" => SystemColor::MarkText,
            "SelectedItem" => SystemColor::SelectedItem,
            "SelectedItemText" => SystemColor::SelectedItemText,
            "VisitedText" => SystemColor::VisitedText,
            _ => SystemColor::AccentColor, // Default case
        }
    }
}

impl From<String> for SystemColor {
    fn from(value: String) -> Self {
        SystemColor::from(value.as_str())
    }
}

impl From<&str> for NamedColor {
    fn from(value: &str) -> Self {
        match value.to_lowercase().as_str() {
            "aliceblue" => NamedColor::AliceBlue,
            "antiquewhite" => NamedColor::AntiqueWhite,
            "aqua" => NamedColor::Aqua,
            "aquamarine" => NamedColor::Aquamarine,
            "azure" => NamedColor::Azure,
            "beige" => NamedColor::Beige,
            "bisque" => NamedColor::Bisque,
            "black" => NamedColor::Black,
            "blanchedalmond" => NamedColor::BlanchedAlmond,
            "blue" => NamedColor::Blue,
            "blueviolet" => NamedColor::BlueViolet,
            "brown" => NamedColor::Brown,
            "burlywood" => NamedColor::BurlyWood,
            "cadetblue" => NamedColor::CadetBlue,
            "chartreuse" => NamedColor::Chartreuse,
            "chocolate" => NamedColor::Chocolate,
            "coral" => NamedColor::Coral,
            "cornflowerblue" => NamedColor::CornflowerBlue,
            "cornsilk" => NamedColor::Cornsilk,
            "crimson" => NamedColor::Crimson,
            "cyan" => NamedColor::Cyan,
            "darkblue" => NamedColor::DarkBlue,
            "darkcyan" => NamedColor::DarkCyan,
            "darkgoldenrod" => NamedColor::DarkGoldenRod,
            "darkgray" => NamedColor::DarkGray,
            "darkgreen" => NamedColor::DarkGreen,
            "darkkhaki" => NamedColor::DarkKhaki,
            "darkmagenta" => NamedColor::DarkMagenta,
            "darkolivegreen" => NamedColor::DarkOliveGreen,
            "darkorange" => NamedColor::DarkOrange,
            "darkorchid" => NamedColor::DarkOrchid,
            "darkred" => NamedColor::DarkRed,
            "darksalmon" => NamedColor::DarkSalmon,
            "darkseagreen" => NamedColor::DarkSeaGreen,
            "darkslateblue" => NamedColor::DarkSlateBlue,
            "darkslategray" | "darkslategrey" => NamedColor::DarkSlateGray,
            "darkturquoise" => NamedColor::DarkTurquoise,
            "darkviolet" => NamedColor::DarkViolet,
            "deeppink" => NamedColor::DeepPink,
            "deepskyblue" => NamedColor::DeepSkyBlue,
            "dimgray" | "dimgrey" => NamedColor::DimGray,
            "dodgerblue" => NamedColor::DodgerBlue,
            "firebrick" => NamedColor::FireBrick,
            "floralwhite" => NamedColor::FloralWhite,
            "forestgreen" => NamedColor::ForestGreen,
            "fuchsia" => NamedColor::Fuchsia,
            "gainsboro" => NamedColor::Gainsboro,
            "ghostwhite" => NamedColor::GhostWhite,
            "gold" => NamedColor::Gold,
            "goldenrod" => NamedColor::GoldenRod,
            "gray" | "grey" => NamedColor::Gray,
            "green" => NamedColor::Green,
            "greenyellow" => NamedColor::GreenYellow,
            "honeydew" => NamedColor::HoneyDew,
            "hotpink" => NamedColor::HotPink,
            "indianred" => NamedColor::IndianRed,
            "indigo" => NamedColor::Indigo,
            "ivory" => NamedColor::Ivory,
            "khaki" => NamedColor::Khaki,
            "lavender" => NamedColor::Lavender,
            "lavenderblush" => NamedColor::LavenderBlush,
            "lawngreen" => NamedColor::LawnGreen,
            "lemonchiffon" => NamedColor::LemonChiffon,
            "lightblue" => NamedColor::LightBlue,
            "lightcoral" => NamedColor::LightCoral,
            "lightcyan" => NamedColor::LightCyan,
            "lightgoldenrodyellow" => NamedColor::LightGoldenRodYellow,
            "lightgray" | "lightgrey" => NamedColor::LightGray,
            "lightgreen" => NamedColor::LightGreen,
            "lightpink" => NamedColor::LightPink,
            "lightsalmon" => NamedColor::LightSalmon,
            "lightseagreen" => NamedColor::LightSeaGreen,
            "lightskyblue" => NamedColor::LightSkyBlue,
            "lightslategray" | "lightslategrey" => NamedColor::LightSlateGray,
            "lightsteelblue" => NamedColor::LightSteelBlue,
            "lightyellow" => NamedColor::LightYellow,
            "lime" => NamedColor::Lime,
            "limegreen" => NamedColor::LimeGreen,
            "linen" => NamedColor::Linen,
            "magenta" => NamedColor::Magenta,
            "maroon" => NamedColor::Maroon,
            "mediumaquamarine" => NamedColor::MediumAquaMarine,
            "mediumblue" => NamedColor::MediumBlue,
            "mediumorchid" => NamedColor::MediumOrchid,
            "mediumpurple" => NamedColor::MediumPurple,
            "mediumseagreen" => NamedColor::MediumSeaGreen,
            "mediumslateblue" => NamedColor::MediumSlateBlue,
            "mediumspringgreen" => NamedColor::MediumSpringGreen,
            "mediumturquoise" => NamedColor::MediumTurquoise,
            "mediumvioletred" => NamedColor::MediumVioletRed,
            "midnightblue" => NamedColor::MidnightBlue,
            "mintcream" => NamedColor::MintCream,
            "mistyrose" => NamedColor::MistyRose,
            "moccasin" => NamedColor::Moccasin,
            "mavajowhite" => NamedColor::NavajoWhite,
            "navy" => NamedColor::Navy,
            "oldlace" => NamedColor::OldLace,
            "olive" => NamedColor::Olive,
            "olivedrab" => NamedColor::OliveDrab,
            "orange" => NamedColor::Orange,
            "orangered" => NamedColor::OrangeRed,
            "orchid" => NamedColor::Orchid,
            "palegoldenrod" => NamedColor::PaleGoldenRod,
            "palegreen" => NamedColor::PaleGreen,
            "paleturquoise" => NamedColor::PaleTurquoise,
            "palevioletred" => NamedColor::PaleVioletRed,
            "papayawhip" => NamedColor::PapayaWhip,
            "peachpuff" => NamedColor::PeachPuff,
            "peru" => NamedColor::Peru,
            "pink" => NamedColor::Pink,
            "plum" => NamedColor::Plum,
            "powderblue" => NamedColor::PowderBlue,
            "purple" => NamedColor::Purple,
            "rebeccapurple" => NamedColor::RebeccaPurple,
            "red" => NamedColor::Red,
            "rosybrown" => NamedColor::RosyBrown,
            "royalblue" => NamedColor::RoyalBlue,
            "saddlebrown" => NamedColor::SaddleBrown,
            "salmon" => NamedColor::Salmon,
            "sandybrown" => NamedColor::SandyBrown,
            "seagreen" => NamedColor::SeaGreen,
            "seashell" => NamedColor::SeaShell,
            "sienna" => NamedColor::Sienna,
            "silver" => NamedColor::Silver,
            "skyblue" => NamedColor::SkyBlue,
            "slateblue" => NamedColor::SlateBlue,
            "slategray" | "slategrey" => NamedColor::SlateGray,
            "snow" => NamedColor::Snow,
            "springgreen" => NamedColor::SpringGreen,
            "steelblue" => NamedColor::SteelBlue,
            "tan" => NamedColor::Tan,
            "teal" => NamedColor::Teal,
            "thistle" => NamedColor::Thistle,
            "tomato" => NamedColor::Tomato,
            "transparent" => NamedColor::Transparent,
            "turquoise" => NamedColor::Turquoise,
            "violet" => NamedColor::Violet,
            "wheat" => NamedColor::Violet,
            "white" => NamedColor::White,
            "whitesmoke" => NamedColor::WhiteSmoke,
            "yellow" => NamedColor::Yellow,
            "yellowgreen" => NamedColor::YellowGreen,
            _ => NamedColor::default(),
        }
    }
}

impl From<String> for NamedColor {
    fn from(value: String) -> Self {
        NamedColor::from(value.as_str())
    }
}
