[package]
name = "html-parser"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = { workspace = true }
api = { path = "../api" }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "parser_benches"
harness = false
